name: plist_parser
description: A Flutter Plugin for Plist parser supporting XML and Binary formats.
version: 0.0.5
repository: https://github.com/dirablue/plist_parser

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  xml: ^5.3.1
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.1
